"""add pack table

Revision ID: 1aaed4005f23
Revises: aff253e8bb3b
Create Date: 2025-06-26 19:54:22.654876+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1aaed4005f23"
down_revision: Union[str, Sequence[str], None] = "aff253e8bb3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pack")
    # ### end Alembic commands ###
