"""add relationships to card table

Revision ID: 75520981c9a1
Revises: 7375ea55da57
Create Date: 2025-06-26 20:22:45.056279+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75520981c9a1"
down_revision: Union[str, Sequence[str], None] = "7375ea55da57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card", sa.Column("set_id", sa.Text(), nullable=False))
    op.add_column("card", sa.Column("pack_id", sa.Integer(), nullable=True))
    op.create_foreign_key("pack_id_fkey", "card", "pack", ["pack_id"], ["id"])
    op.create_foreign_key(
        "scryfall_id_fkey", "card", "scryfall_card", ["scryfall_id"], ["scryfall_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("scryfall_id_fkey", "card", type_="foreignkey")
    op.drop_constraint("pack_id_fkey", "card", type_="foreignkey")
    op.drop_column("card", "pack_id")
    op.drop_column("card", "set_id")
    # ### end Alembic commands ###
