"""add more scryfall_card columns

Revision ID: 98541ab27ee9
Revises: a1426a996800
Create Date: 2025-06-24 02:00:16.087952+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98541ab27ee9"
down_revision: Union[str, Sequence[str], None] = "a1426a996800"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scryfall_card", sa.Column("oracle_id", sa.String(), nullable=True))
    op.add_column(
        "scryfall_card", sa.Column("multiverse_ids", sa.JSON(), nullable=True)
    )
    op.add_column("scryfall_card", sa.Column("mtgo_id", sa.Integer(), nullable=True))
    op.add_column("scryfall_card", sa.Column("arena_id", sa.Integer(), nullable=True))
    op.add_column(
        "scryfall_card", sa.Column("tcgplayer_id", sa.Integer(), nullable=True)
    )
    op.add_column("scryfall_card", sa.Column("lang", sa.String(), nullable=False))
    op.add_column(
        "scryfall_card", sa.Column("released_at", sa.String(), nullable=False)
    )
    op.add_column("scryfall_card", sa.Column("uri", sa.Text(), nullable=False))
    op.add_column("scryfall_card", sa.Column("scryfall_uri", sa.Text(), nullable=False))
    op.add_column("scryfall_card", sa.Column("layout", sa.String(), nullable=False))
    op.add_column(
        "scryfall_card", sa.Column("highres_image", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "scryfall_card", sa.Column("image_status", sa.String(), nullable=False)
    )
    op.add_column("scryfall_card", sa.Column("image_uris", sa.JSON(), nullable=True))
    op.add_column("scryfall_card", sa.Column("cmc", sa.Float(), nullable=True))
    op.add_column("scryfall_card", sa.Column("type_line", sa.String(), nullable=True))
    op.add_column("scryfall_card", sa.Column("oracle_text", sa.Text(), nullable=True))
    op.add_column("scryfall_card", sa.Column("colors", sa.JSON(), nullable=True))
    op.add_column(
        "scryfall_card", sa.Column("color_identity", sa.JSON(), nullable=True)
    )
    op.add_column("scryfall_card", sa.Column("keywords", sa.JSON(), nullable=True))
    op.add_column("scryfall_card", sa.Column("produced_mana", sa.JSON(), nullable=True))
    op.add_column("scryfall_card", sa.Column("legalities", sa.JSON(), nullable=True))
    op.add_column("scryfall_card", sa.Column("games", sa.JSON(), nullable=True))
    op.add_column("scryfall_card", sa.Column("reserved", sa.Boolean(), nullable=False))
    op.add_column(
        "scryfall_card", sa.Column("game_changer", sa.Boolean(), nullable=False)
    )
    op.add_column("scryfall_card", sa.Column("foil", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("nonfoil", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("finishes", sa.JSON(), nullable=False))
    op.add_column("scryfall_card", sa.Column("oversized", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("promo", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("reprint", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("variation", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("set_id", sa.String(), nullable=False))
    op.add_column("scryfall_card", sa.Column("set", sa.String(), nullable=False))
    op.add_column("scryfall_card", sa.Column("set_name", sa.String(), nullable=False))
    op.add_column("scryfall_card", sa.Column("set_type", sa.String(), nullable=False))
    op.add_column("scryfall_card", sa.Column("set_uri", sa.Text(), nullable=False))
    op.add_column(
        "scryfall_card", sa.Column("set_search_uri", sa.Text(), nullable=False)
    )
    op.add_column(
        "scryfall_card", sa.Column("scryfall_set_uri", sa.Text(), nullable=False)
    )
    op.add_column("scryfall_card", sa.Column("rulings_uri", sa.Text(), nullable=False))
    op.add_column(
        "scryfall_card", sa.Column("prints_search_uri", sa.Text(), nullable=False)
    )
    op.add_column(
        "scryfall_card", sa.Column("collector_number", sa.String(), nullable=False)
    )
    op.add_column("scryfall_card", sa.Column("digital", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("rarity", sa.String(), nullable=False))
    op.add_column(
        "scryfall_card", sa.Column("card_back_id", sa.String(), nullable=True)
    )
    op.add_column("scryfall_card", sa.Column("artist", sa.String(), nullable=False))
    op.add_column("scryfall_card", sa.Column("artist_ids", sa.JSON(), nullable=True))
    op.add_column(
        "scryfall_card", sa.Column("illustration_id", sa.String(), nullable=True)
    )
    op.add_column(
        "scryfall_card", sa.Column("border_color", sa.String(), nullable=False)
    )
    op.add_column("scryfall_card", sa.Column("frame", sa.String(), nullable=False))
    op.add_column("scryfall_card", sa.Column("full_art", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("textless", sa.Boolean(), nullable=False))
    op.add_column("scryfall_card", sa.Column("booster", sa.Boolean(), nullable=False))
    op.add_column(
        "scryfall_card", sa.Column("story_spotlight", sa.Boolean(), nullable=False)
    )
    op.add_column("scryfall_card", sa.Column("prices", sa.JSON(), nullable=True))
    op.add_column("scryfall_card", sa.Column("related_uris", sa.JSON(), nullable=True))
    op.add_column("scryfall_card", sa.Column("purchase_uris", sa.JSON(), nullable=True))
    op.alter_column(
        "scryfall_card",
        "scryfall_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "scryfall_card",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scryfall_card",
        "name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "scryfall_card",
        "scryfall_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("scryfall_card", "purchase_uris")
    op.drop_column("scryfall_card", "related_uris")
    op.drop_column("scryfall_card", "prices")
    op.drop_column("scryfall_card", "story_spotlight")
    op.drop_column("scryfall_card", "booster")
    op.drop_column("scryfall_card", "textless")
    op.drop_column("scryfall_card", "full_art")
    op.drop_column("scryfall_card", "frame")
    op.drop_column("scryfall_card", "border_color")
    op.drop_column("scryfall_card", "illustration_id")
    op.drop_column("scryfall_card", "artist_ids")
    op.drop_column("scryfall_card", "artist")
    op.drop_column("scryfall_card", "card_back_id")
    op.drop_column("scryfall_card", "rarity")
    op.drop_column("scryfall_card", "digital")
    op.drop_column("scryfall_card", "collector_number")
    op.drop_column("scryfall_card", "prints_search_uri")
    op.drop_column("scryfall_card", "rulings_uri")
    op.drop_column("scryfall_card", "scryfall_set_uri")
    op.drop_column("scryfall_card", "set_search_uri")
    op.drop_column("scryfall_card", "set_uri")
    op.drop_column("scryfall_card", "set_type")
    op.drop_column("scryfall_card", "set_name")
    op.drop_column("scryfall_card", "set")
    op.drop_column("scryfall_card", "set_id")
    op.drop_column("scryfall_card", "variation")
    op.drop_column("scryfall_card", "reprint")
    op.drop_column("scryfall_card", "promo")
    op.drop_column("scryfall_card", "oversized")
    op.drop_column("scryfall_card", "finishes")
    op.drop_column("scryfall_card", "nonfoil")
    op.drop_column("scryfall_card", "foil")
    op.drop_column("scryfall_card", "game_changer")
    op.drop_column("scryfall_card", "reserved")
    op.drop_column("scryfall_card", "games")
    op.drop_column("scryfall_card", "legalities")
    op.drop_column("scryfall_card", "produced_mana")
    op.drop_column("scryfall_card", "keywords")
    op.drop_column("scryfall_card", "color_identity")
    op.drop_column("scryfall_card", "colors")
    op.drop_column("scryfall_card", "oracle_text")
    op.drop_column("scryfall_card", "type_line")
    op.drop_column("scryfall_card", "cmc")
    op.drop_column("scryfall_card", "image_uris")
    op.drop_column("scryfall_card", "image_status")
    op.drop_column("scryfall_card", "highres_image")
    op.drop_column("scryfall_card", "layout")
    op.drop_column("scryfall_card", "scryfall_uri")
    op.drop_column("scryfall_card", "uri")
    op.drop_column("scryfall_card", "released_at")
    op.drop_column("scryfall_card", "lang")
    op.drop_column("scryfall_card", "tcgplayer_id")
    op.drop_column("scryfall_card", "arena_id")
    op.drop_column("scryfall_card", "mtgo_id")
    op.drop_column("scryfall_card", "multiverse_ids")
    op.drop_column("scryfall_card", "oracle_id")
    # ### end Alembic commands ###
