"""create scryfall_card table

Revision ID: a1426a996800
Revises:
Create Date: 2025-06-22 18:26:46.450103+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1426a996800"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scryfall_card",
        sa.Column("scryfall_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mana_cost", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scryfall_card_name"), "scryfall_card", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_scryfall_card_scryfall_id"),
        "scryfall_card",
        ["scryfall_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scryfall_card_scryfall_id"), table_name="scryfall_card")
    op.drop_index(op.f("ix_scryfall_card_name"), table_name="scryfall_card")
    op.drop_table("scryfall_card")
    # ### end Alembic commands ###
